version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: million-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: million_properties
    volumes:
      - mongodb_data:/data/db
      - ./db/seed:/docker-entrypoint-initdb.d
    networks:
      - million-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: million-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - million-network

  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: million-api
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;https://+:5001
      - ConnectionStrings__MongoDB=mongodb://admin:password123@mongodb:27017/million_properties?authSource=admin
    depends_on:
      - mongodb
    networks:
      - million-network
    volumes:
      - ../apps/api:/app
      - /app/bin
      - /app/obj

  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    container_name: million-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - million-network
    volumes:
      - ../apps/web:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongodb_data:

networks:
  million-network:
    driver: bridge
